version: '3'

services:

    web:
        restart:  always
        image: manager:dev
        build: 
            context: .
            dockerfile: local.dockerfile
        command: bash run.sh
        container_name: web-manager
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        environment:
            RUNIN_IN_CONTAINER: "True"
            DEBUG: "True"
            DJANGO_DB: postgresql
            POSTGRES_HOST: postgres
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432

    postgres:
        image: postgres:13.0-alpine
        container_name: postgres
        restart:  always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: