from manager.views.index import IndexView
from manager.views.login import Loginview
from manager.views.logout import LogoutView
from manager.views.register import RegisterView
from manager.views.list_users import ListUsersView
from manager.views.user_detail import UserDetailView
from manager.views.update_user import UpdateUserView
from manager.views.create_user import CreateUserView
from manager.views.delete_user import DeleteUserView
from manager.views.massive_users_delete import MassiveUsersDeleteView
from manager.views.massive_users_update import MassiveUsersUpdateView
from manager.views.manager import ManagerView
