# Generated by Django 4.2.2 on 2023-06-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_userprofilemodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Other'), (1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
