# Generated by Django 4.2.2 on 2023-06-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_userprofilemodel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='address',
            new_name='street',
        ),
    ]
